DROP TABLE IF EXISTS PRODUCT;
 
CREATE TABLE PRODUCT (
    PRODUCT_ID serial PRIMARY KEY NOT NULL,
    NAME varchar(100) NOT NULL,
    AGE smallint NOT NULL
);

INSERT INTO PRODUCT(PRODUCT_ID, NAME, AGE) values
    (1,'Park', 20),
    (2,'Kwon', 15)
;